-- RETIRED: pre-SaaS global stock push installer.
-- StOmni SaaS uses tenant-aware operational_alerts instead.
-- Runtime implementation:
--   supabase/migrations/20260908051000_saas_operational_alerts_automation.sql
--   supabase/migrations/20260908051200_saas_operational_alert_event_driven_stock.sql
--
-- Intentionally no executable SQL. Do not recreate the old
-- trigger_stock_alert_evaluar_tx or OneSignal included_segments=All flow.
