BEGIN;

-- Pricing is resolved in PostgreSQL so modified clients cannot invent a lower
-- line price. Rules are generic: they target a product/presentation, quantity
-- threshold and optional time window; no sector-specific branching exists.
CREATE TABLE public.sale_price_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  product_id bigint NOT NULL REFERENCES public.productos(id) ON DELETE CASCADE,
  presentation_code text NULL,
  min_quantity numeric NOT NULL DEFAULT 1,
  fixed_price numeric NULL,
  discount_percent numeric NULL,
  priority integer NOT NULL DEFAULT 0,
  starts_at timestamptz NULL,
  ends_at timestamptz NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sale_price_rule_name CHECK (
    length(trim(name)) BETWEEN 1 AND 100 AND name !~ '[[:cntrl:]]'
  ),
  CONSTRAINT sale_price_rule_presentation CHECK (
    presentation_code IS NULL OR presentation_code ~ '^[a-z][a-z0-9_]{0,39}$'
  ),
  CONSTRAINT sale_price_rule_quantity CHECK (
    min_quantity > 0 AND min_quantity::text NOT IN ('NaN','Infinity','-Infinity')
  ),
  CONSTRAINT sale_price_rule_value CHECK (
    (fixed_price IS NOT NULL)::integer + (discount_percent IS NOT NULL)::integer = 1
    AND (fixed_price IS NULL OR (fixed_price >= 0 AND fixed_price::text NOT IN ('NaN','Infinity','-Infinity')))
    AND (discount_percent IS NULL OR discount_percent > 0 AND discount_percent <= 100)
  ),
  CONSTRAINT sale_price_rule_window CHECK (
    ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at
  )
);

CREATE INDEX sale_price_rules_resolution_idx
  ON public.sale_price_rules(product_id, active, priority DESC, min_quantity DESC);

ALTER TABLE public.sale_price_rules ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sale_price_rules FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.sale_price_rules TO authenticated;
CREATE POLICY sale_price_rules_read ON public.sale_price_rules
FOR SELECT TO authenticated USING (public.app_empleado_activo());

CREATE OR REPLACE FUNCTION public._catalog_commercial_price_v1(
  p_product_id bigint,
  p_presentation_code text
)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  v_product public.productos%ROWTYPE;
  v_profile jsonb;
  v_presentation jsonb;
  v_code text := lower(trim(coalesce(p_presentation_code,'')));
  v_type text;
  v_pcs integer;
  v_unit numeric;
  v_box_base numeric;
  v_factor numeric;
BEGIN
  SELECT * INTO v_product FROM public.productos
  WHERE id=p_product_id AND coalesce(activo,true);
  IF NOT FOUND THEN RAISE EXCEPTION 'Producto inexistente o inactivo'; END IF;

  SELECT profile INTO v_profile FROM public.product_unit_profiles
  WHERE product_id=p_product_id;
  IF FOUND THEN
    SELECT value INTO v_presentation
    FROM jsonb_array_elements(v_profile->'presentations')
    WHERE value->>'code'=v_code;
    IF v_presentation IS NULL THEN
      RAISE EXCEPTION 'La presentación no pertenece al producto';
    END IF;
    v_factor := (v_presentation->>'factor')::numeric;
    -- The current configurable-unit client treats precio_unidad as the base
    -- commercial price and derives every presentation through its factor.
    v_unit := coalesce(v_product.precio_unidad,0);
    v_box_base := coalesce(v_product.precio_caja,0);
    IF v_unit <= 0 THEN v_unit := v_box_base; END IF;
    RETURN round(greatest(v_unit,0) * v_factor, 4);
  END IF;

  v_type := upper(trim(coalesce(v_product.tipo_venta,'')));
  v_pcs := greatest(coalesce(v_product.cantidad_por_caja,1),1);
  v_unit := coalesce(v_product.precio_unidad,0);
  v_box_base := coalesce(v_product.precio_caja,0);

  v_code := CASE
    WHEN v_code IN ('cajas','box','bx') THEN 'caja'
    WHEN v_code IN ('paquetes','paq','pack','pk') THEN 'paquete'
    WHEN v_code IN ('unidades','und','niu','pieza','piezas') THEN 'unidad'
    ELSE v_code
  END;

  IF v_code='caja' THEN
    IF v_type NOT IN ('CAJA_PAQUETES','CAJA+PAQUETES','CAJA + PAQUETES',
                      'CAJA_UNIDADES','CAJA+UNIDADES','CAJA + UNIDADES',
                      'CAJA','SOLO_CAJAS','AMBOS','CAJA_UNIDAD','CAJAS_UNIDADES') THEN
      RAISE EXCEPTION 'El producto no admite venta por caja';
    END IF;
    RETURN round((CASE WHEN v_box_base>0 THEN v_box_base ELSE v_unit END) * v_pcs,4);
  ELSIF v_code='paquete' THEN
    IF v_type IN ('PAQUETES','PAQUETE') THEN
      RETURN round((CASE WHEN v_box_base>0 THEN v_box_base ELSE v_unit END) * v_pcs,4);
    ELSIF v_type IN ('CAJA_PAQUETES','CAJA+PAQUETES','CAJA + PAQUETES') THEN
      RETURN round(CASE WHEN v_unit>0 THEN v_unit ELSE v_box_base END,4);
    END IF;
    RAISE EXCEPTION 'El producto no admite venta por paquete';
  ELSIF v_code='unidad' THEN
    IF v_type NOT IN ('CAJA_UNIDADES','CAJA+UNIDADES','CAJA + UNIDADES',
                      'UNIDAD','SOLO_UNIDADES','AMBOS','CAJA_UNIDAD','CAJAS_UNIDADES') THEN
      RAISE EXCEPTION 'El producto no admite venta por unidad';
    END IF;
    RETURN round(CASE WHEN v_unit>0 THEN v_unit ELSE v_box_base END,4);
  END IF;
  RAISE EXCEPTION 'Presentación comercial desconocida';
END;
$function$;

CREATE OR REPLACE FUNCTION public.resolve_sale_price_v1(
  p_product_id bigint,
  p_presentation_code text,
  p_quantity numeric,
  p_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  v_base numeric;
  v_rule public.sale_price_rules%ROWTYPE;
  v_price numeric;
BEGIN
  IF NOT public.app_empleado_activo() THEN
    RAISE EXCEPTION 'Acceso denegado' USING ERRCODE='42501';
  END IF;
  IF p_quantity IS NULL OR p_quantity<=0 OR p_quantity::text IN ('NaN','Infinity','-Infinity') THEN
    RAISE EXCEPTION 'Cantidad inválida';
  END IF;
  v_base := public._catalog_commercial_price_v1(p_product_id,p_presentation_code);

  SELECT * INTO v_rule
  FROM public.sale_price_rules r
  WHERE r.product_id=p_product_id
    AND r.active
    AND (r.presentation_code IS NULL OR r.presentation_code=lower(trim(p_presentation_code)))
    AND p_quantity>=r.min_quantity
    AND (r.starts_at IS NULL OR p_at>=r.starts_at)
    AND (r.ends_at IS NULL OR p_at<r.ends_at)
  ORDER BY r.priority DESC, r.min_quantity DESC, r.id DESC
  LIMIT 1;

  IF FOUND THEN
    v_price := CASE
      WHEN v_rule.fixed_price IS NOT NULL THEN v_rule.fixed_price
      ELSE v_base * (1 - v_rule.discount_percent/100)
    END;
  ELSE
    v_price := v_base;
  END IF;
  v_price := round(greatest(v_price,0),4);

  RETURN jsonb_build_object(
    'product_id',p_product_id,
    'presentation_code',lower(trim(p_presentation_code)),
    'quantity',p_quantity,
    'catalog_price',v_base,
    'price',v_price,
    'rule_id',CASE WHEN FOUND THEN v_rule.id ELSE NULL END,
    'rule_name',CASE WHEN FOUND THEN v_rule.name ELSE NULL END
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.list_sale_price_rules_v1()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE v_result jsonb;
BEGIN
  IF NOT public.app_tiene_permiso('products.change_price') THEN
    RAISE EXCEPTION 'No autorizado para administrar precios' USING ERRCODE='42501';
  END IF;
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'id',r.id,'name',r.name,'product_id',r.product_id,'product_name',p.nombre,
    'presentation_code',r.presentation_code,'min_quantity',r.min_quantity,
    'fixed_price',r.fixed_price,'discount_percent',r.discount_percent,
    'priority',r.priority,'starts_at',r.starts_at,'ends_at',r.ends_at,'active',r.active
  ) ORDER BY r.priority DESC,r.id DESC),'[]'::jsonb)
  INTO v_result
  FROM public.sale_price_rules r JOIN public.productos p ON p.id=r.product_id;
  RETURN v_result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.save_sale_price_rule_v1(
  p_id bigint,
  p_name text,
  p_product_id bigint,
  p_presentation_code text,
  p_min_quantity numeric,
  p_fixed_price numeric,
  p_discount_percent numeric,
  p_priority integer,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_active boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE v_id bigint;
BEGIN
  IF NOT public.app_tiene_permiso('products.change_price') THEN
    RAISE EXCEPTION 'No autorizado para administrar precios' USING ERRCODE='42501';
  END IF;
  IF p_name IS NULL OR length(trim(p_name)) NOT BETWEEN 1 AND 100
     OR p_product_id IS NULL OR p_product_id<=0
     OR p_min_quantity IS NULL OR p_min_quantity<=0
     OR ((p_fixed_price IS NOT NULL)::integer+(p_discount_percent IS NOT NULL)::integer)<>1
     OR (p_fixed_price IS NOT NULL AND p_fixed_price<0)
     OR (p_discount_percent IS NOT NULL AND (p_discount_percent<=0 OR p_discount_percent>100))
     OR (p_ends_at IS NOT NULL AND p_starts_at IS NOT NULL AND p_ends_at<=p_starts_at) THEN
    RAISE EXCEPTION 'Regla de precio inválida';
  END IF;
  PERFORM 1 FROM public.productos WHERE id=p_product_id AND coalesce(activo,true);
  IF NOT FOUND THEN RAISE EXCEPTION 'Producto inexistente o inactivo'; END IF;
  IF p_presentation_code IS NOT NULL THEN
    PERFORM public._catalog_commercial_price_v1(p_product_id,lower(trim(p_presentation_code)));
  END IF;

  IF p_id IS NULL THEN
    INSERT INTO public.sale_price_rules(name,product_id,presentation_code,min_quantity,
      fixed_price,discount_percent,priority,starts_at,ends_at,active)
    VALUES(trim(p_name),p_product_id,NULLIF(lower(trim(p_presentation_code)),''),p_min_quantity,
      p_fixed_price,p_discount_percent,coalesce(p_priority,0),p_starts_at,p_ends_at,coalesce(p_active,true))
    RETURNING id INTO v_id;
  ELSE
    UPDATE public.sale_price_rules SET
      name=trim(p_name),product_id=p_product_id,
      presentation_code=NULLIF(lower(trim(p_presentation_code)),''),min_quantity=p_min_quantity,
      fixed_price=p_fixed_price,discount_percent=p_discount_percent,priority=coalesce(p_priority,0),
      starts_at=p_starts_at,ends_at=p_ends_at,active=coalesce(p_active,true),updated_at=now()
    WHERE id=p_id RETURNING id INTO v_id;
    IF v_id IS NULL THEN RAISE EXCEPTION 'Regla de precio inexistente'; END IF;
  END IF;
  RETURN jsonb_build_object('id',v_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.delete_sale_price_rule_v1(p_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
  IF NOT public.app_tiene_permiso('products.change_price') THEN
    RAISE EXCEPTION 'No autorizado para administrar precios' USING ERRCODE='42501';
  END IF;
  DELETE FROM public.sale_price_rules WHERE id=p_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Regla de precio inexistente'; END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public._assert_authorized_sale_prices_v1(
  p_detalles jsonb,
  p_fecha timestamptz,
  p_cotizacion_id bigint
)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  v_detail jsonb;
  v_resolved jsonb;
  v_expected numeric;
  v_sent numeric;
  v_quantity numeric;
BEGIN
  -- A quotation freezes its own line prices. Existing quotation conversion
  -- remains valid even if the catalog or promotions change afterwards.
  IF p_cotizacion_id IS NOT NULL THEN RETURN; END IF;
  FOR v_detail IN SELECT value FROM jsonb_array_elements(p_detalles) LOOP
    v_quantity:=NULLIF(v_detail->>'cantidad','')::numeric;
    v_sent:=NULLIF(v_detail->>'precio_unitario_comercial','')::numeric;
    IF v_sent IS NULL THEN v_sent:=NULLIF(v_detail->>'precio','')::numeric; END IF;
    v_resolved:=public.resolve_sale_price_v1(
      (v_detail->>'producto_id')::bigint,
      v_detail->>'tipo_unidad',
      v_quantity,
      coalesce(p_fecha,now())
    );
    v_expected:=(v_resolved->>'price')::numeric;
    IF v_sent IS NULL OR abs(v_sent-v_expected)>0.01 THEN
      RAISE EXCEPTION 'El precio de venta cambió o no está autorizado para el producto %',
        v_detail->>'producto_id' USING ERRCODE='23514';
    END IF;
  END LOOP;
END;
$function$;

-- Replace only the public permission wrappers. The hardened transaction and
-- fractional normalization underneath remain unchanged.
CREATE OR REPLACE FUNCTION public.process_sale_v4(
  p_request_id uuid,p_cliente_id bigint,p_total numeric,p_fecha timestamptz,
  p_es_credito boolean,p_monto_abono numeric,p_detalles jsonb,p_pagos jsonb,
  p_cotizacion_id bigint,p_vendedor_id bigint,p_tipo_comprobante text,
  p_descuento_global_porcentaje numeric,p_descuento_global_monto numeric,
  p_motivo_descuento text,p_subtotal_bruto numeric,p_descuento_autorizado_por bigint
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public
AS $function$
BEGIN
  IF NOT public.app_tiene_permiso('sales.create') THEN
    RAISE EXCEPTION 'No autorizado para registrar ventas' USING ERRCODE='42501';
  END IF;
  IF coalesce(p_descuento_global_monto,0)>0 AND NOT public.app_tiene_permiso('sales.discount') THEN
    RAISE EXCEPTION 'No autorizado para aplicar descuentos' USING ERRCODE='42501';
  END IF;
  PERFORM public._assert_authorized_sale_prices_v1(p_detalles,p_fecha,p_cotizacion_id);
  RETURN public.process_sale_v3(p_request_id,p_cliente_id,p_total,p_fecha,p_es_credito,
    p_monto_abono,p_detalles,p_pagos,p_cotizacion_id,p_vendedor_id,p_tipo_comprobante,
    p_descuento_global_porcentaje,p_descuento_global_monto,p_motivo_descuento,
    p_subtotal_bruto,p_descuento_autorizado_por);
END;
$function$;

CREATE OR REPLACE FUNCTION public.process_sale_with_units_v4(
  p_request_id uuid,p_cliente_id bigint,p_total numeric,p_fecha timestamptz,
  p_es_credito boolean,p_monto_abono numeric,p_detalles jsonb,p_pagos jsonb,
  p_cotizacion_id bigint,p_vendedor_id bigint,p_tipo_comprobante text,
  p_descuento_global_porcentaje numeric,p_descuento_global_monto numeric,
  p_motivo_descuento text,p_subtotal_bruto numeric,p_descuento_autorizado_por bigint
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public
AS $function$
BEGIN
  IF NOT public.app_tiene_permiso('sales.create') THEN
    RAISE EXCEPTION 'No autorizado para registrar ventas' USING ERRCODE='42501';
  END IF;
  IF coalesce(p_descuento_global_monto,0)>0 AND NOT public.app_tiene_permiso('sales.discount') THEN
    RAISE EXCEPTION 'No autorizado para aplicar descuentos' USING ERRCODE='42501';
  END IF;
  PERFORM public._assert_authorized_sale_prices_v1(p_detalles,p_fecha,p_cotizacion_id);
  RETURN public.process_sale_with_units_v3(p_request_id,p_cliente_id,p_total,p_fecha,p_es_credito,
    p_monto_abono,p_detalles,p_pagos,p_cotizacion_id,p_vendedor_id,p_tipo_comprobante,
    p_descuento_global_porcentaje,p_descuento_global_monto,p_motivo_descuento,
    p_subtotal_bruto,p_descuento_autorizado_por);
END;
$function$;

REVOKE ALL ON FUNCTION public._catalog_commercial_price_v1(bigint,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public._assert_authorized_sale_prices_v1(jsonb,timestamptz,bigint) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.resolve_sale_price_v1(bigint,text,numeric,timestamptz) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.list_sale_price_rules_v1() FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.save_sale_price_rule_v1(bigint,text,bigint,text,numeric,numeric,numeric,integer,timestamptz,timestamptz,boolean) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.delete_sale_price_rule_v1(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.resolve_sale_price_v1(bigint,text,numeric,timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_sale_price_rules_v1() TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_sale_price_rule_v1(bigint,text,bigint,text,numeric,numeric,numeric,integer,timestamptz,timestamptz,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_sale_price_rule_v1(bigint) TO authenticated;

COMMIT;