-- Aditiva: agrupa productos reales como variantes sin duplicar inventario.
BEGIN;

CREATE TABLE public.product_variant_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
  attribute_names jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid NOT NULL DEFAULT auth.uid(),
  CHECK (jsonb_typeof(attribute_names) = 'array'),
  CHECK (jsonb_array_length(attribute_names) BETWEEN 1 AND 8)
);

CREATE TABLE public.product_variant_members (
  group_id bigint NOT NULL REFERENCES public.product_variant_groups(id) ON DELETE CASCADE,
  product_id bigint NOT NULL UNIQUE REFERENCES public.productos(id),
  attributes jsonb NOT NULL,
  PRIMARY KEY (group_id, product_id),
  CHECK (jsonb_typeof(attributes) = 'object')
);

ALTER TABLE public.product_variant_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_variant_members ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.product_variant_groups, public.product_variant_members
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public._product_variant_group_json(p_group_id bigint)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
  SELECT jsonb_build_object(
    'id', g.id,
    'name', g.name,
    'attribute_names', g.attribute_names,
    'members', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'product_id', m.product_id,
        'product_name', p.nombre,
        'product_code', coalesce(p.codigo,''),
        'attributes', m.attributes
      ) ORDER BY p.nombre, m.product_id)
      FROM public.product_variant_members m
      JOIN public.productos p ON p.id = m.product_id
      WHERE m.group_id = g.id
    ), '[]'::jsonb)
  )
  FROM public.product_variant_groups g
  WHERE g.id = p_group_id;
$function$;

CREATE OR REPLACE FUNCTION public.list_product_variant_groups_v1()
RETURNS SETOF jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE v_id bigint;
BEGIN
  IF NOT public.app_tiene_permiso('products.update') THEN
    RAISE EXCEPTION 'No autorizado para consultar variantes' USING ERRCODE='42501';
  END IF;
  FOR v_id IN SELECT id FROM public.product_variant_groups ORDER BY name,id LOOP
    RETURN NEXT public._product_variant_group_json(v_id);
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.save_product_variant_group_v1(
  p_group_id bigint,
  p_name text,
  p_attribute_names jsonb,
  p_members jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  v_id bigint;
  v_member jsonb;
  v_product_id bigint;
  v_attributes jsonb;
  v_attribute text;
  v_signature text;
  v_signatures text[] := ARRAY[]::text[];
BEGIN
  IF NOT public.app_tiene_permiso('products.update') THEN
    RAISE EXCEPTION 'No autorizado para modificar variantes' USING ERRCODE='42501';
  END IF;
  IF nullif(trim(coalesce(p_name,'')),'') IS NULL OR length(trim(p_name)) > 120
     OR p_attribute_names IS NULL OR jsonb_typeof(p_attribute_names) <> 'array'
     OR jsonb_array_length(p_attribute_names) NOT BETWEEN 1 AND 8
     OR p_members IS NULL OR jsonb_typeof(p_members) <> 'array'
     OR jsonb_array_length(p_members) NOT BETWEEN 2 AND 200 THEN
    RAISE EXCEPTION 'Grupo de variantes inválido' USING ERRCODE='22023';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(p_attribute_names) value
    WHERE nullif(trim(value),'') IS NULL OR length(trim(value)) > 40
  ) OR (
    SELECT count(*) FROM jsonb_array_elements_text(p_attribute_names)
  ) <> (
    SELECT count(DISTINCT lower(trim(value)))
    FROM jsonb_array_elements_text(p_attribute_names) value
  ) THEN
    RAISE EXCEPTION 'Atributos de variante inválidos o duplicados' USING ERRCODE='22023';
  END IF;

  IF p_group_id IS NULL THEN
    INSERT INTO public.product_variant_groups(name,attribute_names)
    VALUES(trim(p_name),p_attribute_names) RETURNING id INTO v_id;
  ELSE
    SELECT id INTO v_id FROM public.product_variant_groups
      WHERE id=p_group_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Grupo de variantes inexistente' USING ERRCODE='P0002'; END IF;
    UPDATE public.product_variant_groups SET
      name=trim(p_name), attribute_names=p_attribute_names, updated_at=now()
      WHERE id=v_id;
    DELETE FROM public.product_variant_members WHERE group_id=v_id;
  END IF;

  FOR v_member IN SELECT value FROM jsonb_array_elements(p_members) LOOP
    v_product_id := NULLIF(v_member->>'product_id','')::bigint;
    v_attributes := v_member->'attributes';
    IF v_product_id IS NULL OR v_attributes IS NULL OR jsonb_typeof(v_attributes)<>'object' THEN
      RAISE EXCEPTION 'Miembro de variante inválido' USING ERRCODE='22023';
    END IF;
    PERFORM 1 FROM public.productos WHERE id=v_product_id AND coalesce(activo,true)=true;
    IF NOT FOUND THEN RAISE EXCEPTION 'Producto variante no disponible' USING ERRCODE='23503'; END IF;

    v_signature := '';
    FOR v_attribute IN SELECT lower(trim(value)) FROM jsonb_array_elements_text(p_attribute_names) value LOOP
      IF nullif(trim(v_attributes->>v_attribute),'') IS NULL THEN
        RAISE EXCEPTION 'Falta un atributo en una variante' USING ERRCODE='22023';
      END IF;
      v_signature := v_signature || '|' || lower(trim(v_attributes->>v_attribute));
    END LOOP;
    IF v_signature = ANY(v_signatures) THEN
      RAISE EXCEPTION 'Combinación de variante duplicada' USING ERRCODE='23505';
    END IF;
    v_signatures := array_append(v_signatures,v_signature);

    INSERT INTO public.product_variant_members(group_id,product_id,attributes)
    VALUES(v_id,v_product_id,v_attributes);
  END LOOP;

  RETURN public._product_variant_group_json(v_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.delete_product_variant_group_v1(p_group_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,public
AS $function$
BEGIN
  IF NOT public.app_tiene_permiso('products.update') THEN
    RAISE EXCEPTION 'No autorizado para eliminar variantes' USING ERRCODE='42501';
  END IF;
  DELETE FROM public.product_variant_groups WHERE id=p_group_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Grupo de variantes inexistente' USING ERRCODE='P0002'; END IF;
END;
$function$;

REVOKE ALL ON FUNCTION public._product_variant_group_json(bigint) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.list_product_variant_groups_v1() FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.save_product_variant_group_v1(bigint,text,jsonb,jsonb) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.delete_product_variant_group_v1(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.list_product_variant_groups_v1() TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_product_variant_group_v1(bigint,text,jsonb,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_product_variant_group_v1(bigint) TO authenticated;

COMMIT;
