-- Fase 6.1 SaaS: auditoría empresarial transversal, append-only y tenant-aware.
BEGIN;

CREATE TABLE public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  actor_user_id uuid,
  actor_employee_id bigint,
  actor_label text,
  actor_role text,
  action text NOT NULL CHECK (action ~ '^[a-z][a-z0-9_.-]{2,80}$'),
  entity_type text NOT NULL CHECK (entity_type ~ '^[a-z][a-z0-9_.-]{1,80}$'),
  entity_id text,
  source_table text NOT NULL,
  source_operation text NOT NULL CHECK (source_operation IN ('INSERT','UPDATE','DELETE','RPC','SYSTEM')),
  request_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata)='object'),
  CHECK (pg_column_size(metadata) <= 32768)
);

COMMENT ON TABLE public.audit_logs IS 'Ledger empresarial append-only de acciones críticas. Metadata limitada y allowlisted; no almacena payloads completos ni secretos.';
COMMENT ON COLUMN public.audit_logs.actor_user_id IS 'auth.uid() observado al producir el evento; snapshot histórico, sin FK para preservar trazabilidad tras bajas.';
COMMENT ON COLUMN public.audit_logs.metadata IS 'Metadata segura y acotada. Nunca debe almacenar tokens, contraseñas, secretos, blobs ni filas completas.';

CREATE INDEX audit_logs_organization_time_idx
  ON public.audit_logs(organization_id, occurred_at DESC, id DESC);
CREATE INDEX audit_logs_organization_action_idx
  ON public.audit_logs(organization_id, action, id DESC);
CREATE INDEX audit_logs_organization_entity_idx
  ON public.audit_logs(organization_id, entity_type, entity_id, id DESC)
  WHERE entity_id IS NOT NULL;

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY audit_logs_tenant_admin_select
ON public.audit_logs
FOR SELECT TO authenticated
USING (
  private.has_permission('tenant.admin')
  AND private.row_belongs_to_current_organization(organization_id)
);

REVOKE ALL ON TABLE public.audit_logs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.audit_logs_id_seq FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.audit_pick_fields(
  p_row jsonb,
  p_fields text[]
)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
SECURITY INVOKER
SET search_path=''
AS $$
  SELECT coalesce(jsonb_object_agg(k, p_row->k), '{}'::jsonb)
  FROM unnest(coalesce(p_fields,'{}'::text[])) AS k
  WHERE p_row ? k
$$;

CREATE OR REPLACE FUNCTION private.audit_changed_fields(
  p_old jsonb,
  p_new jsonb,
  p_allowlist text[]
)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
SECURITY INVOKER
SET search_path=''
AS $$
  SELECT coalesce(jsonb_agg(k ORDER BY k), '[]'::jsonb)
  FROM unnest(coalesce(p_allowlist,'{}'::text[])) AS k
  WHERE (p_old->k) IS DISTINCT FROM (p_new->k)
$$;

CREATE OR REPLACE FUNCTION private.write_audit_log(
  p_organization_id uuid,
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_source_table text,
  p_source_operation text,
  p_request_id uuid DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_session_org uuid := private.current_organization_id();
  v_user uuid := auth.uid();
  v_employee_id bigint;
  v_employee_label text;
  v_role text;
  v_id bigint;
  v_metadata jsonb := coalesce(p_metadata,'{}'::jsonb);
BEGIN
  IF p_organization_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE='23502', MESSAGE='Audit organization_id is required';
  END IF;
  IF v_user IS NOT NULL AND v_session_org IS DISTINCT FROM p_organization_id THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Cross-tenant audit event is not allowed';
  END IF;
  IF p_action IS NULL OR p_entity_type IS NULL OR p_source_table IS NULL OR p_source_operation IS NULL THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Audit event fields are required';
  END IF;
  IF jsonb_typeof(v_metadata)<>'object' OR pg_column_size(v_metadata)>32768 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Audit metadata must be a JSON object <= 32 KiB';
  END IF;

  IF v_user IS NOT NULL THEN
    SELECT e.id, nullif(btrim(e.nombre),'')
      INTO v_employee_id, v_employee_label
    FROM public.empleados e
    WHERE e.organization_id=p_organization_id
      AND e.app_user_id=v_user
    ORDER BY e.id
    LIMIT 1;
    v_role:=private.current_base_role();
  ELSIF current_user='service_role' THEN
    v_role:='service_role';
    v_employee_label:='service_role';
  ELSE
    v_role:=current_user;
    v_employee_label:=current_user;
  END IF;

  INSERT INTO public.audit_logs(
    organization_id,actor_user_id,actor_employee_id,actor_label,actor_role,
    action,entity_type,entity_id,source_table,source_operation,request_id,metadata
  ) VALUES (
    p_organization_id,v_user,v_employee_id,v_employee_label,v_role,
    lower(p_action),lower(p_entity_type),nullif(p_entity_id,''),
    p_source_table,upper(p_source_operation),p_request_id,v_metadata
  )
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION private.audit_logs_immutable()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
BEGIN
  RAISE EXCEPTION USING ERRCODE='55000', MESSAGE='audit_logs is append-only';
END;
$$;

CREATE TRIGGER audit_logs_block_mutation
BEFORE UPDATE OR DELETE ON public.audit_logs
FOR EACH ROW EXECUTE FUNCTION private.audit_logs_immutable();

REVOKE ALL ON FUNCTION private.audit_pick_fields(jsonb,text[]) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION private.audit_changed_fields(jsonb,jsonb,text[]) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION private.write_audit_log(uuid,text,text,text,text,text,uuid,jsonb) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION private.audit_logs_immutable() FROM PUBLIC,anon,authenticated;

-- Trigger genérico para cambios con allowlist de metadata. TG_ARGV:
-- action, entity_type, comma-separated fields.
CREATE OR REPLACE FUNCTION private.audit_allowlisted_change_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_old jsonb := CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) ELSE '{}'::jsonb END;
  v_new jsonb := CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) ELSE '{}'::jsonb END;
  v_row jsonb := CASE WHEN TG_OP='DELETE' THEN v_old ELSE v_new END;
  v_fields text[] := string_to_array(coalesce(TG_ARGV[2],''),',');
  v_before jsonb;
  v_after jsonb;
  v_metadata jsonb;
  v_org uuid;
  v_entity_id text;
  v_request_id uuid;
BEGIN
  v_org:=nullif(v_row->>'organization_id','')::uuid;
  IF v_org IS NULL THEN v_org:=private.require_current_organization_id(); END IF;
  v_entity_id:=coalesce(
    nullif(v_row->>'id',''), nullif(v_row->>'request_id',''),
    nullif(v_row->>'role_id',''), nullif(v_row->>'employee_id',''),
    nullif(v_row->>'product_id',''), nullif(v_row->>'producto_id','')
  );
  BEGIN v_request_id:=nullif(v_row->>'request_id','')::uuid; EXCEPTION WHEN invalid_text_representation THEN v_request_id:=NULL; END;

  IF TG_OP='UPDATE' THEN
    v_before:=private.audit_pick_fields(v_old,v_fields);
    v_after:=private.audit_pick_fields(v_new,v_fields);
    IF v_before=v_after THEN RETURN NEW; END IF;
    v_metadata:=jsonb_build_object('before',v_before,'after',v_after);
  ELSIF TG_OP='INSERT' THEN
    v_metadata:=jsonb_build_object('values',private.audit_pick_fields(v_new,v_fields));
  ELSE
    v_metadata:=jsonb_build_object('values',private.audit_pick_fields(v_old,v_fields));
  END IF;

  PERFORM private.write_audit_log(
    v_org,TG_ARGV[0],TG_ARGV[1],v_entity_id,TG_TABLE_NAME,TG_OP,v_request_id,v_metadata
  );
  RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END;
$$;
REVOKE ALL ON FUNCTION private.audit_allowlisted_change_trigger() FROM PUBLIC,anon,authenticated;

-- Cambios de precio del producto.
CREATE TRIGGER productos_audit_price_change
AFTER UPDATE OF precio_unidad,precio_caja,precio_compra ON public.productos
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'price.changed','catalog_item','precio_unidad,precio_caja,precio_compra'
);

-- Reglas de precio/promoción.
CREATE TRIGGER sale_price_rules_audit_change
AFTER INSERT OR UPDATE OR DELETE ON public.sale_price_rules
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'price_rule.changed','sale_price_rule','product_id,unit_code,min_base_quantity,price,discount_percentage,active,revision'
);

-- Mermas/ajustes/correcciones de inventario: no duplica ventas, compras o traslados ordinarios.
CREATE OR REPLACE FUNCTION private.audit_inventory_adjustment_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_tipo text := lower(btrim(coalesce(NEW.tipo,'')));
  v_obs text := lower(btrim(coalesce(NEW.observaciones,'')));
  v_entity_id text := coalesce(NEW.id::text,NEW.producto_id::text);
BEGIN
  IF v_tipo NOT IN ('merma','ajuste','correccion','corrección')
     AND v_obs NOT LIKE '%ajuste%'
     AND v_obs NOT LIKE '%merma%'
     AND v_obs NOT LIKE '%correcci%' THEN
    RETURN NEW;
  END IF;

  PERFORM private.write_audit_log(
    NEW.organization_id,
    CASE WHEN v_tipo='merma' OR v_obs LIKE '%merma%' THEN 'stock.shrinkage' ELSE 'stock.adjusted' END,
    'inventory_movement',v_entity_id,TG_TABLE_NAME,TG_OP,NEW.request_id,
    jsonb_strip_nulls(jsonb_build_object(
      'product_id',NEW.producto_id,
      'warehouse_id',NEW.almacen_id,
      'movement_type',NEW.tipo,
      'balance',NEW.saldo,
      'incoming_quantity',NEW.ingreso_cant,
      'outgoing_quantity',NEW.salida_cant,
      'reason',left(coalesce(NEW.observaciones,''),500)
    ))
  );
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.audit_inventory_adjustment_trigger() FROM PUBLIC,anon,authenticated;

CREATE TRIGGER inventario_movimientos_audit_adjustment
AFTER INSERT ON public.inventario_movimientos
FOR EACH ROW EXECUTE FUNCTION private.audit_inventory_adjustment_trigger();

-- Anulaciones de ventas. La tabla ya contiene snapshot operativo/fiscal; audit_logs
-- sólo conserva identificadores, actor y motivo resumido, nunca vuelve a copiarlo.
CREATE TRIGGER ventas_requests_anulados_audit
AFTER INSERT OR UPDATE OF motivo,anulada_por,anulada_por_empleado_id,anulada_at
ON public.ventas_requests_anulados
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'sale.cancelled','sale','venta_id_original,motivo,anulada_por_empleado_id,anulada_por_nombre_snapshot,anulada_at'
);

-- Descuentos sensibles: registra sólo ventas con descuento y sólo campos de autorización.
CREATE OR REPLACE FUNCTION private.audit_sale_discount_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_old_amount numeric := coalesce(OLD.descuento_global_monto,0);
  v_old_pct numeric := coalesce(OLD.descuento_global_porcentaje,0);
  v_new_amount numeric := coalesce(NEW.descuento_global_monto,0);
  v_new_pct numeric := coalesce(NEW.descuento_global_porcentaje,0);
BEGIN
  IF TG_OP='UPDATE'
     AND v_old_amount=v_new_amount
     AND v_old_pct=v_new_pct
     AND OLD.descuento_autorizado_por IS NOT DISTINCT FROM NEW.descuento_autorizado_por
     AND OLD.motivo_descuento IS NOT DISTINCT FROM NEW.motivo_descuento THEN
    RETURN NEW;
  END IF;
  IF v_new_amount<=0 AND v_new_pct<=0 THEN RETURN NEW; END IF;

  PERFORM private.write_audit_log(
    NEW.organization_id,'discount.applied','sale',NEW.id::text,TG_TABLE_NAME,TG_OP,NEW.request_id,
    jsonb_strip_nulls(jsonb_build_object(
      'discount_amount',NEW.descuento_global_monto,
      'discount_percentage',NEW.descuento_global_porcentaje,
      'authorized_by_employee_id',NEW.descuento_autorizado_por,
      'reason',left(coalesce(NEW.motivo_descuento,''),500),
      'gross_subtotal',NEW.subtotal_bruto,
      'sale_total',NEW.total
    ))
  );
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.audit_sale_discount_trigger() FROM PUBLIC,anon,authenticated;

CREATE TRIGGER ventas_audit_sensitive_discount
AFTER INSERT OR UPDATE OF descuento_global_monto,descuento_global_porcentaje,descuento_autorizado_por,motivo_descuento
ON public.ventas
FOR EACH ROW EXECUTE FUNCTION private.audit_sale_discount_trigger();

-- Permisos/RBAC.
CREATE TRIGGER role_permissions_audit_change
AFTER INSERT OR UPDATE OR DELETE ON public.role_permissions
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'permission.role.changed','role_permission','role_id,permission_code'
);

CREATE TRIGGER employee_roles_audit_change
AFTER INSERT OR UPDATE OR DELETE ON public.employee_roles
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'permission.employee_role.changed','employee_role','employee_id,role_id'
);

CREATE TRIGGER employee_permission_overrides_audit_change
AFTER INSERT OR UPDATE OR DELETE ON public.employee_permission_overrides
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'permission.override.changed','employee_permission_override','employee_id,permission_code,allowed'
);

-- Capacidades por empresa: allowlist explícita, sin payloads ajenos.
CREATE TRIGGER business_capabilities_audit_change
AFTER UPDATE ON public.business_capabilities
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'configuration.capabilities.changed','business_capabilities','inventory_enabled,multiple_branches,multiple_warehouses,credit_sales,electronic_invoicing,supplier_management,purchase_management,lot_tracking,expiry_tracking,variants,services,serial_number_tracking,revision'
);

-- Definiciones de campos configurables, sin valores de entidades.
CREATE TRIGGER custom_field_definitions_audit_change
AFTER INSERT OR UPDATE OR DELETE ON public.custom_field_definitions
FOR EACH ROW EXECUTE FUNCTION private.audit_allowlisted_change_trigger(
  'configuration.custom_field.changed','custom_field_definition','entity_type,code,label,value_type,required,active,sort_order,item_types'
);

-- Configuración principal: sólo nombres de campos cambiados; no se copian valores,
-- firmas, certificados, tokens ni otros secretos potenciales.
CREATE OR REPLACE FUNCTION private.audit_business_configuration_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_allow text[] := ARRAY[
    'nombre_negocio','razon_social','ruc','direccion','telefono','email',
    'moneda','timezone','logo_url','serie_boleta','serie_factura','serie_nota_credito'
  ];
  v_changed jsonb;
BEGIN
  v_changed:=private.audit_changed_fields(to_jsonb(OLD),to_jsonb(NEW),v_allow);
  IF jsonb_array_length(v_changed)=0 THEN RETURN NEW; END IF;
  PERFORM private.write_audit_log(
    NEW.organization_id,'configuration.business.changed','business_configuration',NEW.id::text,
    TG_TABLE_NAME,TG_OP,NULL,jsonb_build_object('changed_fields',v_changed)
  );
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.audit_business_configuration_trigger() FROM PUBLIC,anon,authenticated;

CREATE TRIGGER configuracion_negocio_audit_change
AFTER UPDATE ON public.configuracion_negocio
FOR EACH ROW EXECUTE FUNCTION private.audit_business_configuration_trigger();

-- Lectura paginada/filtrada. No se concede SELECT directo a Data API.
CREATE OR REPLACE FUNCTION public.list_audit_logs_v1(
  p_limit integer DEFAULT 100,
  p_before_id bigint DEFAULT NULL,
  p_action text DEFAULT NULL,
  p_entity_type text DEFAULT NULL
)
RETURNS SETOF jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path=''
AS $$
DECLARE
  v_org uuid := private.require_current_organization_id();
  v_limit integer := coalesce(p_limit,100);
BEGIN
  IF NOT private.has_permission('tenant.admin') THEN
    RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Not authorized to read enterprise audit logs';
  END IF;
  IF v_limit<1 OR v_limit>200 THEN
    RAISE EXCEPTION USING ERRCODE='22023', MESSAGE='Audit page size must be between 1 and 200';
  END IF;

  RETURN QUERY
  SELECT jsonb_build_object(
    'id',a.id,
    'occurred_at',a.occurred_at,
    'actor_user_id',a.actor_user_id,
    'actor_employee_id',a.actor_employee_id,
    'actor_label',a.actor_label,
    'actor_role',a.actor_role,
    'action',a.action,
    'entity_type',a.entity_type,
    'entity_id',a.entity_id,
    'source_table',a.source_table,
    'source_operation',a.source_operation,
    'request_id',a.request_id,
    'metadata',a.metadata
  )
  FROM public.audit_logs a
  WHERE a.organization_id=v_org
    AND (p_before_id IS NULL OR a.id<p_before_id)
    AND (nullif(btrim(coalesce(p_action,'')),'') IS NULL OR a.action=p_action)
    AND (nullif(btrim(coalesce(p_entity_type,'')),'') IS NULL OR a.entity_type=p_entity_type)
  ORDER BY a.id DESC
  LIMIT v_limit;
END;
$$;

REVOKE ALL ON FUNCTION public.list_audit_logs_v1(integer,bigint,text,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.list_audit_logs_v1(integer,bigint,text,text) TO authenticated;

COMMIT;
