BEGIN;

CREATE TABLE public.product_traceability_configs (
  product_id bigint PRIMARY KEY REFERENCES public.productos(id) ON DELETE CASCADE,
  mode text NOT NULL DEFAULT 'none' CHECK (mode IN ('none','lot','serial')),
  expiry_required boolean NOT NULL DEFAULT false,
  revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT traceability_expiry_mode CHECK (NOT expiry_required OR mode='lot')
);

CREATE TABLE public.inventory_lots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.productos(id),
  warehouse_id bigint NOT NULL REFERENCES public.almacenes(id),
  lot_code text NOT NULL,
  expiry_date date NULL,
  base_quantity numeric(20,6) NOT NULL DEFAULT 0 CHECK (base_quantity >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT inventory_lot_code_valid CHECK (
    length(trim(lot_code)) BETWEEN 1 AND 100 AND lot_code !~ '[[:cntrl:]]'
  ),
  UNIQUE(product_id,warehouse_id,lot_code)
);

CREATE TABLE public.inventory_serials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.productos(id),
  warehouse_id bigint NOT NULL REFERENCES public.almacenes(id),
  serial_number text NOT NULL,
  status text NOT NULL DEFAULT 'in_stock' CHECK (
    status IN ('in_stock','sold','transferred','written_off')
  ),
  received_request_id uuid NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT inventory_serial_number_valid CHECK (
    length(trim(serial_number)) BETWEEN 1 AND 160 AND serial_number !~ '[[:cntrl:]]'
  ),
  UNIQUE(product_id,serial_number)
);

CREATE TABLE public.inventory_traceability_receipts (
  request_id uuid PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.productos(id),
  warehouse_id bigint NOT NULL REFERENCES public.almacenes(id),
  mode text NOT NULL CHECK (mode IN ('lot','serial')),
  total_base_quantity numeric(20,6) NOT NULL CHECK (total_base_quantity > 0),
  inventory_request_id uuid NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX inventory_lots_product_warehouse_idx
  ON public.inventory_lots(product_id,warehouse_id,expiry_date);
CREATE INDEX inventory_serials_product_warehouse_idx
  ON public.inventory_serials(product_id,warehouse_id,status);

ALTER TABLE public.product_traceability_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_serials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_traceability_receipts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.product_traceability_configs,public.inventory_lots,
  public.inventory_serials,public.inventory_traceability_receipts
  FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.product_traceability_configs,public.inventory_lots,
  public.inventory_serials TO authenticated;
CREATE POLICY product_traceability_configs_read ON public.product_traceability_configs
  FOR SELECT TO authenticated USING (public.app_empleado_activo());
CREATE POLICY inventory_lots_read ON public.inventory_lots
  FOR SELECT TO authenticated USING (public.app_empleado_activo());
CREATE POLICY inventory_serials_read ON public.inventory_serials
  FOR SELECT TO authenticated USING (public.app_empleado_activo());

CREATE OR REPLACE FUNCTION public.get_product_traceability_config_v1(p_product_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public
AS $function$
DECLARE v_config public.product_traceability_configs%ROWTYPE;
BEGIN
  IF NOT public.app_empleado_activo() THEN
    RAISE EXCEPTION 'Acceso denegado' USING ERRCODE='42501';
  END IF;
  PERFORM 1 FROM public.productos WHERE id=p_product_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Producto inexistente' USING ERRCODE='P0002'; END IF;
  SELECT * INTO v_config FROM public.product_traceability_configs WHERE product_id=p_product_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'product_id',p_product_id,'mode','none','expiry_required',false,'revision',0
    );
  END IF;
  RETURN jsonb_build_object(
    'product_id',v_config.product_id,'mode',v_config.mode,
    'expiry_required',v_config.expiry_required,'revision',v_config.revision
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.save_product_traceability_config_v1(
  p_product_id bigint,
  p_expected_revision bigint,
  p_mode text,
  p_expiry_required boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,public
AS $function$
DECLARE v_current public.product_traceability_configs%ROWTYPE;
BEGIN
  IF NOT public.app_tiene_permiso('products.update') THEN
    RAISE EXCEPTION 'No autorizado para configurar trazabilidad' USING ERRCODE='42501';
  END IF;
  IF p_product_id IS NULL OR p_product_id<=0 OR p_expected_revision IS NULL OR p_expected_revision<0
     OR p_mode NOT IN ('none','lot','serial')
     OR (coalesce(p_expiry_required,false) AND p_mode<>'lot') THEN
    RAISE EXCEPTION 'Configuración de trazabilidad inválida' USING ERRCODE='22023';
  END IF;
  PERFORM 1 FROM public.productos WHERE id=p_product_id AND coalesce(activo,true) FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Producto inexistente o inactivo' USING ERRCODE='P0002'; END IF;
  SELECT * INTO v_current FROM public.product_traceability_configs
    WHERE product_id=p_product_id FOR UPDATE;
  IF FOUND THEN
    IF v_current.revision<>p_expected_revision THEN
      RAISE EXCEPTION 'La configuración cambió en otro dispositivo' USING ERRCODE='40001';
    END IF;
    IF v_current.mode<>p_mode AND (
      EXISTS(SELECT 1 FROM public.inventory_lots WHERE product_id=p_product_id AND base_quantity>0)
      OR EXISTS(SELECT 1 FROM public.inventory_serials WHERE product_id=p_product_id AND status='in_stock')
    ) THEN
      RAISE EXCEPTION 'No puedes cambiar el modo mientras exista stock trazable' USING ERRCODE='23514';
    END IF;
    UPDATE public.product_traceability_configs SET
      mode=p_mode,expiry_required=coalesce(p_expiry_required,false),
      revision=revision+1,updated_at=now()
    WHERE product_id=p_product_id;
  ELSE
    IF p_expected_revision<>0 THEN
      RAISE EXCEPTION 'La configuración ya no coincide' USING ERRCODE='40001';
    END IF;
    INSERT INTO public.product_traceability_configs(product_id,mode,expiry_required)
      VALUES(p_product_id,p_mode,coalesce(p_expiry_required,false));
  END IF;
  RETURN public.get_product_traceability_config_v1(p_product_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.list_inventory_lots_v1(
  p_product_id bigint DEFAULT NULL,
  p_warehouse_id bigint DEFAULT NULL
)
RETURNS SETOF jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public
AS $function$
  SELECT jsonb_build_object(
    'id',l.id,'product_id',l.product_id,'product_name',coalesce(p.nombre,''),
    'warehouse_id',l.warehouse_id,'warehouse_name',coalesce(a.nombre,''),
    'lot_code',l.lot_code,'expiry_date',l.expiry_date,'base_quantity',l.base_quantity
  )
  FROM public.inventory_lots l
  JOIN public.productos p ON p.id=l.product_id
  JOIN public.almacenes a ON a.id=l.warehouse_id
  WHERE public.app_empleado_activo()
    AND (p_product_id IS NULL OR l.product_id=p_product_id)
    AND (p_warehouse_id IS NULL OR l.warehouse_id=p_warehouse_id)
  ORDER BY l.expiry_date NULLS LAST,l.lot_code,l.id;
$function$;

CREATE OR REPLACE FUNCTION public.list_inventory_serials_v1(
  p_product_id bigint DEFAULT NULL,
  p_warehouse_id bigint DEFAULT NULL
)
RETURNS SETOF jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,public
AS $function$
  SELECT jsonb_build_object(
    'id',s.id,'product_id',s.product_id,'product_name',coalesce(p.nombre,''),
    'warehouse_id',s.warehouse_id,'warehouse_name',coalesce(a.nombre,''),
    'serial_number',s.serial_number,'status',s.status
  )
  FROM public.inventory_serials s
  JOIN public.productos p ON p.id=s.product_id
  JOIN public.almacenes a ON a.id=s.warehouse_id
  WHERE public.app_empleado_activo()
    AND (p_product_id IS NULL OR s.product_id=p_product_id)
    AND (p_warehouse_id IS NULL OR s.warehouse_id=p_warehouse_id)
  ORDER BY s.serial_number,s.id;
$function$;

CREATE OR REPLACE FUNCTION public.register_traceable_merchandise_receipt_v1(
  p_request_id uuid,
  p_product_id bigint,
  p_warehouse_id bigint,
  p_total_base_quantity numeric,
  p_received_at timestamptz,
  p_entry_type text,
  p_document text,
  p_supplier_id bigint,
  p_observations text,
  p_unit_cost numeric,
  p_unit_price numeric,
  p_box_price numeric,
  p_comparative_box_price numeric,
  p_allocations jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,public
AS $function$
DECLARE
  v_config public.product_traceability_configs%ROWTYPE;
  v_existing public.inventory_traceability_receipts%ROWTYPE;
  v_allocation jsonb;
  v_sum numeric:=0;
  v_qty numeric;
  v_lot text;
  v_expiry date;
  v_serial text;
  v_inventory_request uuid;
  v_scale integer;
BEGIN
  IF NOT public.app_tiene_permiso('inventory.receive') THEN
    RAISE EXCEPTION 'No autorizado para recibir inventario' USING ERRCODE='42501';
  END IF;
  IF p_request_id IS NULL OR p_product_id IS NULL OR p_product_id<=0
     OR p_warehouse_id IS NULL OR p_warehouse_id<=0
     OR p_total_base_quantity IS NULL OR p_total_base_quantity<=0
     OR p_allocations IS NULL OR jsonb_typeof(p_allocations)<>'array'
     OR jsonb_array_length(p_allocations)=0 THEN
    RAISE EXCEPTION 'Recepción trazable inválida' USING ERRCODE='22023';
  END IF;

  SELECT * INTO v_existing FROM public.inventory_traceability_receipts
    WHERE request_id=p_request_id;
  IF FOUND THEN
    IF v_existing.product_id<>p_product_id OR v_existing.warehouse_id<>p_warehouse_id
       OR v_existing.total_base_quantity<>p_total_base_quantity THEN
      RAISE EXCEPTION 'El request_id pertenece a otra recepción' USING ERRCODE='23505';
    END IF;
    RETURN jsonb_build_object('idempotent',true,'inventory_request_id',v_existing.inventory_request_id);
  END IF;

  SELECT * INTO v_config FROM public.product_traceability_configs
    WHERE product_id=p_product_id FOR SHARE;
  IF NOT FOUND OR v_config.mode='none' THEN
    RAISE EXCEPTION 'El producto no tiene trazabilidad habilitada' USING ERRCODE='23514';
  END IF;
  IF v_config.mode='lot' AND NOT EXISTS(
    SELECT 1 FROM public.business_capabilities WHERE business_id=1
  ) THEN RAISE EXCEPTION 'Falta configuración de capacidades'; END IF;

  PERFORM public._visible_base_to_stored(p_product_id,p_total_base_quantity);
  PERFORM 1 FROM public.almacenes WHERE id=p_warehouse_id AND coalesce(activo,true) FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Almacén no disponible' USING ERRCODE='23503'; END IF;

  IF v_config.mode='lot' THEN
    FOR v_allocation IN SELECT value FROM jsonb_array_elements(p_allocations) LOOP
      v_lot:=trim(coalesce(v_allocation->>'lot_code',''));
      v_qty:=NULLIF(v_allocation->>'base_quantity','')::numeric;
      v_expiry:=NULLIF(v_allocation->>'expiry_date','')::date;
      IF v_lot='' OR length(v_lot)>100 OR v_qty IS NULL OR v_qty<=0
         OR (v_config.expiry_required AND v_expiry IS NULL) THEN
        RAISE EXCEPTION 'Asignación de lote inválida' USING ERRCODE='22023';
      END IF;
      PERFORM public._visible_base_to_stored(p_product_id,v_qty);
      v_sum:=v_sum+v_qty;
    END LOOP;
  ELSE
    IF p_total_base_quantity<>trunc(p_total_base_quantity)
       OR jsonb_array_length(p_allocations)<>p_total_base_quantity::integer THEN
      RAISE EXCEPTION 'Debe existir una serie por unidad recibida' USING ERRCODE='22023';
    END IF;
    FOR v_allocation IN SELECT value FROM jsonb_array_elements(p_allocations) LOOP
      v_serial:=trim(coalesce(v_allocation->>'serial_number',''));
      IF v_serial='' OR length(v_serial)>160 THEN
        RAISE EXCEPTION 'Número de serie inválido' USING ERRCODE='22023';
      END IF;
      IF EXISTS(SELECT 1 FROM public.inventory_serials
                WHERE product_id=p_product_id AND lower(serial_number)=lower(v_serial)) THEN
        RAISE EXCEPTION 'La serie % ya existe',v_serial USING ERRCODE='23505';
      END IF;
      v_sum:=v_sum+1;
    END LOOP;
  END IF;

  IF abs(v_sum-p_total_base_quantity)>0.000001 THEN
    RAISE EXCEPTION 'La trazabilidad no coincide con la cantidad recibida' USING ERRCODE='23514';
  END IF;

  v_inventory_request:=gen_random_uuid();
  PERFORM public.registrar_ingreso_mercaderia_scaled_v2(
    v_inventory_request,p_product_id,coalesce(p_received_at,now()),
    coalesce(nullif(trim(p_entry_type),''),'Ingreso trazable'),coalesce(trim(p_document),''),
    p_supplier_id,coalesce(trim(p_observations),''),
    jsonb_build_array(jsonb_build_object('almacen_id',p_warehouse_id,'cantidad_base',p_total_base_quantity)),
    coalesce(p_unit_cost,0),coalesce(p_unit_price,0),coalesce(p_box_price,0),
    coalesce(p_comparative_box_price,0)
  );

  IF v_config.mode='lot' THEN
    FOR v_allocation IN SELECT value FROM jsonb_array_elements(p_allocations) LOOP
      v_lot:=trim(v_allocation->>'lot_code');
      v_qty:=(v_allocation->>'base_quantity')::numeric;
      v_expiry:=NULLIF(v_allocation->>'expiry_date','')::date;
      INSERT INTO public.inventory_lots(product_id,warehouse_id,lot_code,expiry_date,base_quantity)
      VALUES(p_product_id,p_warehouse_id,v_lot,v_expiry,v_qty)
      ON CONFLICT(product_id,warehouse_id,lot_code) DO UPDATE SET
        base_quantity=public.inventory_lots.base_quantity+EXCLUDED.base_quantity,
        expiry_date=CASE
          WHEN public.inventory_lots.expiry_date IS NULL THEN EXCLUDED.expiry_date
          WHEN EXCLUDED.expiry_date IS NULL THEN public.inventory_lots.expiry_date
          WHEN public.inventory_lots.expiry_date=EXCLUDED.expiry_date THEN EXCLUDED.expiry_date
          ELSE NULL
        END,
        updated_at=now();
      IF EXISTS(
        SELECT 1 FROM public.inventory_lots
        WHERE product_id=p_product_id AND warehouse_id=p_warehouse_id AND lot_code=v_lot
          AND expiry_date IS NULL AND v_expiry IS NOT NULL AND v_config.expiry_required
      ) THEN
        RAISE EXCEPTION 'El lote % ya existe con otra fecha de vencimiento',v_lot USING ERRCODE='23514';
      END IF;
    END LOOP;
  ELSE
    FOR v_allocation IN SELECT value FROM jsonb_array_elements(p_allocations) LOOP
      INSERT INTO public.inventory_serials(
        product_id,warehouse_id,serial_number,status,received_request_id
      ) VALUES(
        p_product_id,p_warehouse_id,trim(v_allocation->>'serial_number'),'in_stock',p_request_id
      );
    END LOOP;
  END IF;

  INSERT INTO public.inventory_traceability_receipts(
    request_id,product_id,warehouse_id,mode,total_base_quantity,inventory_request_id
  ) VALUES(
    p_request_id,p_product_id,p_warehouse_id,v_config.mode,p_total_base_quantity,v_inventory_request
  );

  RETURN jsonb_build_object('idempotent',false,'inventory_request_id',v_inventory_request);
END;
$function$;

REVOKE ALL ON FUNCTION public.get_product_traceability_config_v1(bigint) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.save_product_traceability_config_v1(bigint,bigint,text,boolean) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.list_inventory_lots_v1(bigint,bigint) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.list_inventory_serials_v1(bigint,bigint) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.register_traceable_merchandise_receipt_v1(uuid,bigint,bigint,numeric,timestamptz,text,text,bigint,text,numeric,numeric,numeric,numeric,jsonb) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_product_traceability_config_v1(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_product_traceability_config_v1(bigint,bigint,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_inventory_lots_v1(bigint,bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_inventory_serials_v1(bigint,bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_traceable_merchandise_receipt_v1(uuid,bigint,bigint,numeric,timestamptz,text,text,bigint,text,numeric,numeric,numeric,numeric,jsonb) TO authenticated;

COMMIT;