-- Aditiva: órdenes de compra con recepción parcial e inventario fraccionario.
-- No aplicar remotamente hasta ejecutar las pruebas SQL locales del HEAD final.
BEGIN;

-- Extender el catálogo de permisos sin permitir autoescalado de operadores.
ALTER TABLE public.employee_permission_overrides
  DROP CONSTRAINT employee_permission_code_known;
ALTER TABLE public.employee_permission_overrides
  ADD CONSTRAINT employee_permission_code_known CHECK (
    permission_code = ANY (ARRAY[
      'products.create','products.update','products.change_price',
      'inventory.receive','inventory.adjust','sales.create','sales.discount',
      'purchases.manage','reports.view_profit','business.configure'
    ]::text[])
  );

CREATE OR REPLACE FUNCTION public._app_role_base_permissions(p_role text)
RETURNS text[]
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog, public
AS $function$
  SELECT CASE lower(trim(coalesce(p_role, '')))
    WHEN 'admin' THEN ARRAY[
      'products.create','products.update','products.change_price',
      'inventory.receive','inventory.adjust','sales.create','sales.discount',
      'purchases.manage','reports.view_profit','business.configure'
    ]::text[]
    WHEN 'administrador' THEN ARRAY[
      'products.create','products.update','products.change_price',
      'inventory.receive','inventory.adjust','sales.create','sales.discount',
      'purchases.manage','reports.view_profit','business.configure'
    ]::text[]
    WHEN 'operador' THEN ARRAY[
      'inventory.receive','sales.create','sales.discount'
    ]::text[]
    ELSE ARRAY[]::text[]
  END;
$function$;

CREATE OR REPLACE FUNCTION public.get_employee_permission_settings_v1(p_employee_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  v_role text;
  v_base text[];
  v_permissions jsonb;
BEGIN
  IF NOT public.app_es_admin() THEN
    RAISE EXCEPTION 'Solo el administrador puede consultar permisos de empleados'
      USING ERRCODE = '42501';
  END IF;

  SELECT e.rol INTO v_role
  FROM public.empleados e
  WHERE e.id = p_employee_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Empleado no encontrado' USING ERRCODE = 'P0002';
  END IF;

  v_base := public._app_role_base_permissions(v_role);
  SELECT coalesce(
    jsonb_object_agg(code, jsonb_build_object(
      'base_allowed', code = ANY(v_base),
      'allowed', CASE
        WHEN lower(trim(coalesce(v_role, ''))) IN ('admin', 'administrador') THEN true
        WHEN code = ANY(v_base) THEN coalesce((
          SELECT o.allowed
          FROM public.employee_permission_overrides o
          WHERE o.employee_id = p_employee_id AND o.permission_code = code
        ), true)
        ELSE false
      END
    )), '{}'::jsonb
  ) INTO v_permissions
  FROM unnest(ARRAY[
    'products.create','products.update','products.change_price',
    'inventory.receive','inventory.adjust','sales.create','sales.discount',
    'purchases.manage','reports.view_profit','business.configure'
  ]::text[]) AS code;

  RETURN jsonb_build_object(
    'employee_id', p_employee_id,
    'role', lower(trim(v_role)),
    'permissions', v_permissions
  );
END;
$function$;

CREATE TABLE public.purchase_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL UNIQUE,
  supplier_id bigint NOT NULL REFERENCES public.proveedores(id),
  warehouse_id bigint NOT NULL REFERENCES public.almacenes(id),
  status text NOT NULL DEFAULT 'ordered' CHECK (
    status IN ('draft','ordered','partially_received','received','cancelled')
  ),
  ordered_at timestamptz NOT NULL DEFAULT now(),
  expected_at timestamptz NULL,
  notes text NOT NULL DEFAULT '',
  cancelled_reason text NULL,
  created_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expected_at IS NULL OR expected_at >= ordered_at)
);

CREATE TABLE public.purchase_order_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id bigint NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.productos(id),
  ordered_base_quantity numeric(20,6) NOT NULL CHECK (ordered_base_quantity > 0),
  received_base_quantity numeric(20,6) NOT NULL DEFAULT 0 CHECK (received_base_quantity >= 0),
  unit_cost numeric(18,6) NOT NULL CHECK (unit_cost >= 0),
  UNIQUE (purchase_order_id, product_id),
  CHECK (received_base_quantity <= ordered_base_quantity)
);

CREATE TABLE public.purchase_receipts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id uuid NOT NULL UNIQUE,
  purchase_order_id bigint NOT NULL REFERENCES public.purchase_orders(id),
  received_at timestamptz NOT NULL DEFAULT now(),
  document text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  received_by uuid NOT NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.purchase_receipt_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_receipt_id bigint NOT NULL REFERENCES public.purchase_receipts(id) ON DELETE CASCADE,
  purchase_order_line_id bigint NOT NULL REFERENCES public.purchase_order_lines(id),
  base_quantity numeric(20,6) NOT NULL CHECK (base_quantity > 0),
  UNIQUE (purchase_receipt_id, purchase_order_line_id)
);

CREATE INDEX purchase_orders_supplier_idx ON public.purchase_orders(supplier_id, ordered_at DESC);
CREATE INDEX purchase_orders_status_idx ON public.purchase_orders(status, ordered_at DESC);
CREATE INDEX purchase_order_lines_order_idx ON public.purchase_order_lines(purchase_order_id);
CREATE INDEX purchase_receipts_order_idx ON public.purchase_receipts(purchase_order_id, received_at DESC);

ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_receipt_lines ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.purchase_orders, public.purchase_order_lines,
  public.purchase_receipts, public.purchase_receipt_lines FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public._purchase_order_json(p_order_id bigint)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
  SELECT jsonb_build_object(
    'id', o.id,
    'request_id', o.request_id::text,
    'supplier_id', o.supplier_id,
    'supplier_name', coalesce(s.nombre, ''),
    'warehouse_id', o.warehouse_id,
    'warehouse_name', coalesce(a.nombre, ''),
    'status', o.status,
    'ordered_at', o.ordered_at,
    'expected_at', o.expected_at,
    'notes', o.notes,
    'lines', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', l.id,
        'product_id', l.product_id,
        'product_name', coalesce(p.nombre, p.codigo, ''),
        'ordered_base_quantity', l.ordered_base_quantity,
        'received_base_quantity', l.received_base_quantity,
        'unit_cost', l.unit_cost
      ) ORDER BY l.id)
      FROM public.purchase_order_lines l
      JOIN public.productos p ON p.id = l.product_id
      WHERE l.purchase_order_id = o.id
    ), '[]'::jsonb)
  )
  FROM public.purchase_orders o
  JOIN public.proveedores s ON s.id = o.supplier_id
  JOIN public.almacenes a ON a.id = o.warehouse_id
  WHERE o.id = p_order_id;
$function$;

CREATE OR REPLACE FUNCTION public.list_purchase_orders_v1(
  p_status text DEFAULT NULL,
  p_limit integer DEFAULT 100
)
RETURNS SETOF jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE v_id bigint;
BEGIN
  IF NOT public.app_tiene_permiso('purchases.manage') THEN
    RAISE EXCEPTION 'No autorizado para consultar compras' USING ERRCODE = '42501';
  END IF;
  IF p_status IS NOT NULL AND p_status NOT IN
      ('draft','ordered','partially_received','received','cancelled') THEN
    RAISE EXCEPTION 'Estado de orden inválido' USING ERRCODE = '22023';
  END IF;
  FOR v_id IN
    SELECT o.id FROM public.purchase_orders o
    WHERE p_status IS NULL OR o.status = p_status
    ORDER BY o.ordered_at DESC, o.id DESC
    LIMIT greatest(1, least(coalesce(p_limit,100),200))
  LOOP
    RETURN NEXT public._purchase_order_json(v_id);
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.create_purchase_order_v1(
  p_request_id uuid,
  p_supplier_id bigint,
  p_warehouse_id bigint,
  p_ordered_at timestamptz,
  p_expected_at timestamptz,
  p_notes text,
  p_lines jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  v_order_id bigint;
  v_line jsonb;
  v_product_id bigint;
  v_quantity numeric;
  v_cost numeric;
BEGIN
  IF NOT public.app_tiene_permiso('purchases.manage') THEN
    RAISE EXCEPTION 'No autorizado para crear compras' USING ERRCODE = '42501';
  END IF;
  IF p_request_id IS NULL OR p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array'
     OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'Orden de compra inválida' USING ERRCODE = '22023';
  END IF;

  SELECT id INTO v_order_id FROM public.purchase_orders WHERE request_id = p_request_id;
  IF v_order_id IS NOT NULL THEN
    RETURN public._purchase_order_json(v_order_id);
  END IF;

  PERFORM 1 FROM public.proveedores
   WHERE id = p_supplier_id AND coalesce(activo,true) = true
     AND lower(coalesce(estado,'activo')) = 'activo';
  IF NOT FOUND THEN RAISE EXCEPTION 'Proveedor no disponible' USING ERRCODE = '23503'; END IF;
  PERFORM 1 FROM public.almacenes WHERE id = p_warehouse_id AND coalesce(activo,true) = true;
  IF NOT FOUND THEN RAISE EXCEPTION 'Almacén no disponible' USING ERRCODE = '23503'; END IF;
  IF p_expected_at IS NOT NULL AND p_expected_at < p_ordered_at THEN
    RAISE EXCEPTION 'Fecha esperada inválida' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.purchase_orders(
    request_id,supplier_id,warehouse_id,status,ordered_at,expected_at,notes
  ) VALUES (
    p_request_id,p_supplier_id,p_warehouse_id,'ordered',coalesce(p_ordered_at,now()),
    p_expected_at,coalesce(trim(p_notes),'')
  ) RETURNING id INTO v_order_id;

  FOR v_line IN SELECT value FROM jsonb_array_elements(p_lines) LOOP
    v_product_id := NULLIF(v_line->>'product_id','')::bigint;
    v_quantity := NULLIF(v_line->>'base_quantity','')::numeric;
    v_cost := NULLIF(v_line->>'unit_cost','')::numeric;
    IF v_product_id IS NULL OR v_quantity IS NULL OR v_quantity <= 0
       OR v_cost IS NULL OR v_cost < 0 THEN
      RAISE EXCEPTION 'Línea de compra inválida' USING ERRCODE = '22023';
    END IF;
    -- También valida que la cantidad pueda expresarse con la precisión del producto.
    PERFORM public._visible_base_to_stored(v_product_id, v_quantity);
    PERFORM 1 FROM public.productos WHERE id = v_product_id AND coalesce(activo,true) = true;
    IF NOT FOUND THEN RAISE EXCEPTION 'Producto no disponible' USING ERRCODE = '23503'; END IF;
    INSERT INTO public.purchase_order_lines(
      purchase_order_id,product_id,ordered_base_quantity,unit_cost
    ) VALUES (v_order_id,v_product_id,v_quantity,v_cost);
  END LOOP;

  RETURN public._purchase_order_json(v_order_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.receive_purchase_order_v1(
  p_request_id uuid,
  p_purchase_order_id bigint,
  p_received_at timestamptz,
  p_document text,
  p_notes text,
  p_lines jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE
  v_order public.purchase_orders%ROWTYPE;
  v_receipt_id bigint;
  v_existing_order_id bigint;
  v_line jsonb;
  v_order_line public.purchase_order_lines%ROWTYPE;
  v_quantity numeric;
  v_pending numeric;
  v_product public.productos%ROWTYPE;
BEGIN
  IF NOT public.app_tiene_permiso('purchases.manage')
     OR NOT public.app_tiene_permiso('inventory.receive') THEN
    RAISE EXCEPTION 'No autorizado para recibir compras' USING ERRCODE = '42501';
  END IF;
  IF p_request_id IS NULL OR p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array'
     OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'Recepción de compra inválida' USING ERRCODE = '22023';
  END IF;

  SELECT r.purchase_order_id INTO v_existing_order_id
  FROM public.purchase_receipts r WHERE r.request_id = p_request_id;
  IF v_existing_order_id IS NOT NULL THEN
    IF v_existing_order_id <> p_purchase_order_id THEN
      RAISE EXCEPTION 'El request_id pertenece a otra orden' USING ERRCODE = '23505';
    END IF;
    RETURN public._purchase_order_json(v_existing_order_id);
  END IF;

  SELECT * INTO v_order FROM public.purchase_orders
   WHERE id = p_purchase_order_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Orden de compra inexistente' USING ERRCODE = 'P0002'; END IF;
  IF v_order.status NOT IN ('ordered','partially_received') THEN
    RAISE EXCEPTION 'La orden no admite recepciones en su estado actual' USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.purchase_receipts(
    request_id,purchase_order_id,received_at,document,notes
  ) VALUES (
    p_request_id,p_purchase_order_id,coalesce(p_received_at,now()),
    coalesce(trim(p_document),''),coalesce(trim(p_notes),'')
  ) RETURNING id INTO v_receipt_id;

  FOR v_line IN SELECT value FROM jsonb_array_elements(p_lines) LOOP
    SELECT * INTO v_order_line
    FROM public.purchase_order_lines
    WHERE id = NULLIF(v_line->>'purchase_order_line_id','')::bigint
      AND purchase_order_id = p_purchase_order_id
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Línea de compra inexistente' USING ERRCODE = 'P0002'; END IF;

    v_quantity := NULLIF(v_line->>'base_quantity','')::numeric;
    v_pending := v_order_line.ordered_base_quantity - v_order_line.received_base_quantity;
    IF v_quantity IS NULL OR v_quantity <= 0 OR v_quantity > v_pending THEN
      RAISE EXCEPTION 'Cantidad recibida excede lo pendiente' USING ERRCODE = '23514';
    END IF;
    PERFORM public._visible_base_to_stored(v_order_line.product_id, v_quantity);

    INSERT INTO public.purchase_receipt_lines(
      purchase_receipt_id,purchase_order_line_id,base_quantity
    ) VALUES (v_receipt_id,v_order_line.id,v_quantity);

    SELECT * INTO v_product FROM public.productos WHERE id = v_order_line.product_id;
    PERFORM public.registrar_ingreso_mercaderia_scaled_v2(
      gen_random_uuid(), v_order_line.product_id, coalesce(p_received_at,now()),
      'Compra', coalesce(trim(p_document),''), v_order.supplier_id,
      'Recepción OC #' || p_purchase_order_id::text ||
        CASE WHEN nullif(trim(coalesce(p_notes,'')),'') IS NULL THEN '' ELSE ' · ' || trim(p_notes) END,
      jsonb_build_array(jsonb_build_object(
        'almacen_id', v_order.warehouse_id,
        'cantidad_base', v_quantity
      )),
      v_order_line.unit_cost,
      coalesce(v_product.precio_unidad,0),
      coalesce(v_product.precio_caja,0),
      coalesce(v_product.precio_caja,0) * greatest(coalesce(v_product.cantidad_por_caja,1),1)
    );

    UPDATE public.purchase_order_lines
      SET received_base_quantity = received_base_quantity + v_quantity
      WHERE id = v_order_line.id;
  END LOOP;

  UPDATE public.purchase_orders o
  SET status = CASE
      WHEN NOT EXISTS (
        SELECT 1 FROM public.purchase_order_lines l
        WHERE l.purchase_order_id = o.id
          AND l.received_base_quantity < l.ordered_base_quantity
      ) THEN 'received'
      ELSE 'partially_received'
    END,
    updated_at = now()
  WHERE o.id = p_purchase_order_id;

  RETURN public._purchase_order_json(p_purchase_order_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.cancel_purchase_order_v1(
  p_purchase_order_id bigint,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
DECLARE v_order public.purchase_orders%ROWTYPE;
BEGIN
  IF NOT public.app_tiene_permiso('purchases.manage') THEN
    RAISE EXCEPTION 'No autorizado para anular compras' USING ERRCODE = '42501';
  END IF;
  IF nullif(trim(coalesce(p_reason,'')),'') IS NULL THEN
    RAISE EXCEPTION 'Indica el motivo de anulación' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_order FROM public.purchase_orders
    WHERE id = p_purchase_order_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Orden de compra inexistente' USING ERRCODE = 'P0002'; END IF;
  IF v_order.status = 'received' OR EXISTS (
    SELECT 1 FROM public.purchase_order_lines
    WHERE purchase_order_id = p_purchase_order_id AND received_base_quantity > 0
  ) THEN
    RAISE EXCEPTION 'Una orden con mercadería recibida no puede anularse' USING ERRCODE = '23514';
  END IF;
  IF v_order.status = 'cancelled' THEN RETURN public._purchase_order_json(p_purchase_order_id); END IF;
  UPDATE public.purchase_orders SET status='cancelled', cancelled_reason=trim(p_reason), updated_at=now()
    WHERE id=p_purchase_order_id;
  RETURN public._purchase_order_json(p_purchase_order_id);
END;
$function$;

REVOKE ALL ON FUNCTION public._purchase_order_json(bigint) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.list_purchase_orders_v1(text,integer) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.create_purchase_order_v1(uuid,bigint,bigint,timestamptz,timestamptz,text,jsonb) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.receive_purchase_order_v1(uuid,bigint,timestamptz,text,text,jsonb) FROM PUBLIC,anon;
REVOKE ALL ON FUNCTION public.cancel_purchase_order_v1(bigint,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.list_purchase_orders_v1(text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_purchase_order_v1(uuid,bigint,bigint,timestamptz,timestamptz,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.receive_purchase_order_v1(uuid,bigint,timestamptz,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_purchase_order_v1(bigint,text) TO authenticated;

COMMIT;
